name: blue-green-deploy

on: push

env:
    AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
    SPRING_CLOUD_SERVICE: sping-cloud-service
    APP_NAME: gateway
    DEFAULT_DEPLOYMENT: default
    NEW_DEPLOYMENT: green

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file piggymetrics/pom.xml -DskipTests
      
  deploy:
    uses: vermegi/spring-cloud-gh-actions-sample/.github/workflows/blue-green-deploy-job.yml@main
    with: 
      AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
      SPRING_CLOUD_SERVICE: sping-cloud-service
      APP_NAME: gateway
      DEFAULT_DEPLOYMENT: default
      NEW_DEPLOYMENT: green 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}