name: blue-green-deploy-with-subflow

on: push

env:
    AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
    SPRING_CLOUD_SERVICE: sping-cloud-service
    APP_NAME: gateway
    DEFAULT_DEPLOYMENT: default
    NEW_DEPLOYMENT: green

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file piggymetrics/pom.xml -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: ./piggymetrics/${{env.APP_NAME}}/target/${{env.APP_NAME}}.jar

  deploy:
    uses: vermegi/spring-cloud-gh-actions-sample/.github/workflows/blue-green-deploy-job.yml@main
    needs: build
    with: 
      AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
      SPRING_CLOUD_SERVICE: sping-cloud-service
      APP_NAME: gateway
      DEFAULT_DEPLOYMENT: default
      NEW_DEPLOYMENT: green 
      ARTIFACT: jar-file
      JARPATH: ./piggymetrics/gateway/target/gateway.jar
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
