name: blue-green-deploy

on: [workflow_dispatch]

env:
    AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
    SPRING_CLOUD_SERVICE: sping-cloud-service
    GATEWAY_APP_NAME: gateway
    AUTH_APP_NAME: auth_service
    ACCOUNT_APP_NAME: account_service

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file piggymetrics/pom.xml -DskipTests

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az extension add --name spring-cloud
          az config set defaults.group=${{env.AZURE_RESOURCEGROUP_NAME}}
          az config set defaults.spring-cloud=${{env.SPRING_CLOUD_SERVICE}}
          ACTIVEDEPLOYMENT=$(az spring-cloud app show -s sping-cloud-service -g spring-cloud-demos -n gateway --query properties.activeDeployment.name)
          if [ $ACTIVEDEPLOYMENT = 'default' ]; then
            NEWDEPLOYMENT='green'
          else
            NEWDEPLOYMENT='default'
          fi
          az spring-cloud app deployment create --app ${{env.GATEWAY_APP_NAME}} -n $NEWDEPLOYMENT
          az spring-cloud app deploy -n ${{env.GATEWAY_APP_NAME}} --jar-path $GITHUB_WORKSPACE/piggymetrics/${{env.GATEWAY_APP_NAME}}/target/${{env.GATEWAY_APP_NAME}}.jar -d $NEWDEPLOYMENT
          az spring-cloud app set-deployment -d $NEWDEPLOYMENT -n ${{env.GATEWAY_APP_NAME}}
          az spring-cloud app deployment delete --app ${{env.GATEWAY_APP_NAME}} -n $ACTIVEDEPLOYMENT


