name: infra-deploy

on: [workflow_dispatch]

env:
    AZURE_RESOURCEGROUP_NAME: spring-cloud-demos
    SPRING_CLOUD_SERVICE: sping-cloud-service
    GATEWAY_APP_NAME: gateway
    AUTH_APP_NAME: auth_service
    ACCOUNT_APP_NAME: account_service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep
        parameters: spring_cloud_name=${{env.SPRING_CLOUD_SERVICE}} gatewayAppName=${{env.GATEWAY_APP_NAME}} authAppName=${{env.AUTH_APP_NAME}} accountAppName=${{env.ACCOUNT_APP_NAME}}
