name: simple-deploy

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file piggymetrics/pom.xml -DskipTests

  deploy: 

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        